# version: "3.8"

services:
  vending-agent:
    image: registry.rd.ns.co.th/vending-agent:0.0.1
    pull_policy: always
    container_name: vending-agent
    restart: unless-stopped
    ports:
      - "3304:3304"
    environment:
      PORT: 3304

      CUSTOMER_CODE: "wnyh"

      # vending code
      VENDING_CODE: "FFFFFF12"
      DOOR_TYPE_STANDBY: "[1,2,3]"
      DOOR_TYPE_NOW: "[1,2,3]"

      # Mogan
      APP_TIMEZONE: "Asia/Bangkok"
      API_LOG_RETENTION_DAYS: 30

      # Vending
      # ----------------------------
      # สำหรับเครื่อง Windows ให้ใส่ COM Port เป็นชื่อเช่น "COM6"
      # หากรันบน Windows ให้คอนฟิกเป็นค่าแบบนี้:
      SERIAL_VENDING: "COM6" # หรือ “COM3”, “COM4” etc., ตามค่าใน Device Manager

      SERIAL_VENDING_BAUD_RATE: 9600

      # Navigation Lights
      # สำหรับ Windows ใส่ COM Port เช่นเดียวกัน
      SERIAL_NAVIGATION_LIGHTS: "COM144"
      SERIAL_NAVIGATION_LIGHTS_BAUD_RATE: 115200

      # QR NFC
      SERIAL_QR_NFC: "COM3"
      SERIAL_QR_NFC_BAUD_RATE: 115200
      SERIAL_WRITE_TIMEOUT_MS: 3000

      # MQTT (publish qr-nfc serial data)
      MQTT_ENABLED: "true"
      MQTT_BROKER_URL: "mqtt://rd.ns.co.th:1883"
      MQTT_CLIENT_ID: "vending-3d-ctl"
      MQTT_USERNAME: ""
      MQTT_PASSWORD: ""
      MQTT_QRNFC_TOPIC: "hm/${CUSTOMER_CODE}/${VENDING_CODE}/reader"
      MQTT_QRNFC_MIFARE_SIGNATURE: "02,FF,01,09,00"
      MQTT_QRNFC_BARCODE_WNY_SIGNATURE_REGEX: "([0-9a-f\\-]{36})_(\\d{8})_(\\d+)_(\\d+)_(IN|OUT)_(\\d{14})"
      MQTT_QRNFC_QOS: 0
      MQTT_QRNFC_RETAIN: "false"

    volumes:
      - ./logs:/app/logs

    # 
    # หากใช้ Windows: ไม่ต้อง map devices หรือ privileged ใดๆ
    # แค่ระบุ SERIAL_VENDING, SERIAL_NAVIGATION_LIGHTS, SERIAL_QR_NFC เป็นชื่อ COM port (เช่น "COM3", "COM6") ตามที่เห็นใน Device Manager ใน Windows
    #
    # สำหรับ Linux (เท่านั้น):
    #   ถ้าต้องการเข้าถึง serial port เช่น /dev/ttyUSB* ให้เพิ่ม privileged: true ด้วย
    #   และแมป devices ลงไป (uncomment ตามต้องการ)
    # privileged: true
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
    #   - "/dev/ttyUSB1:/dev/ttyUSB1"
    #   - "/dev/ttyUSB2:/dev/ttyUSB2"
