export const MANUAL_TEST_COMMANDS = [
  {
    id: "health",
    group: "Status",
    title: "Health snapshot",
    method: "GET",
    endpoint: "/api/v1/health",
    protected: false,
    risk: "read",
    focus: { area: "system" },
    description: "Read process, serial, MQTT, queue policy, and alert state.",
    defaultBody: null,
    controls: [],
  },
  {
    id: "jobQueue",
    group: "Status",
    title: "Serial write queue",
    method: "GET",
    endpoint: "/api/v1/job/que",
    protected: false,
    risk: "read",
    focus: { area: "queue" },
    description: "Read per-port queued and running serial writes.",
    defaultBody: null,
    controls: [],
  },
  {
    id: "vendingRawWrite",
    group: "Raw serial",
    title: "Vending raw hex write",
    method: "POST",
    endpoint: "/api/v1/serial/vending/write",
    protected: true,
    risk: "hardware-write",
    focus: { area: "vending", transport: "vending" },
    description: "Send even-length hex directly to the vending serial port and wait for RX.",
    defaultBody: { data: "EE010000" },
    controls: [
      {
        path: ["data"],
        label: "Hex payload",
        type: "hex",
        placeholder: "EE010000",
      },
    ],
  },
  {
    id: "navigationLightsWrite",
    group: "Navigation lights",
    title: "LED range write",
    method: "POST",
    endpoint: "/api/v1/serial/navigation-lights/write",
    protected: true,
    risk: "hardware-write",
    focus: { area: "navigationLights", ledStartPath: ["data", "cmd", 0], ledEndPath: ["data", "cmd", 1] },
    description: "Send LED range command and wait for RX with configured retry policy.",
    defaultBody: { data: { act: "led", cmd: [1, 165, 0, 128, 0, 1] } },
    controls: [
      { path: ["data", "cmd", 0], label: "First LED", type: "number", min: 1, max: 165 },
      { path: ["data", "cmd", 1], label: "Last LED", type: "number", min: 1, max: 165 },
      { path: ["data", "cmd", 2], label: "R", type: "number", min: 0, max: 255 },
      { path: ["data", "cmd", 3], label: "G", type: "number", min: 0, max: 255 },
      { path: ["data", "cmd", 4], label: "B", type: "number", min: 0, max: 255 },
      {
        path: ["data", "cmd", 5],
        label: "Mode",
        type: "select",
        options: [
          { value: 0, label: "Steady" },
          { value: 1, label: "Flash" },
        ],
      },
    ],
  },
  {
    id: "navigationLightsNoWait",
    group: "Navigation lights",
    title: "LED write no-wait",
    method: "POST",
    endpoint: "/api/v1/serial/navigation-lights/write-no-wait",
    protected: true,
    risk: "hardware-write",
    focus: { area: "navigationLights", ledStartPath: ["data", "cmd", 0], ledEndPath: ["data", "cmd", 1] },
    description: "Send LED range command and return after TX/drain without waiting for RX.",
    defaultBody: { data: { act: "led", cmd: [1, 165, 0, 128, 0, 1] } },
    controls: [
      { path: ["data", "cmd", 0], label: "First LED", type: "number", min: 1, max: 165 },
      { path: ["data", "cmd", 1], label: "Last LED", type: "number", min: 1, max: 165 },
      { path: ["data", "cmd", 2], label: "R", type: "number", min: 0, max: 255 },
      { path: ["data", "cmd", 3], label: "G", type: "number", min: 0, max: 255 },
      { path: ["data", "cmd", 4], label: "B", type: "number", min: 0, max: 255 },
      {
        path: ["data", "cmd", 5],
        label: "Mode",
        type: "select",
        options: [
          { value: 0, label: "Steady" },
          { value: 1, label: "Flash" },
        ],
      },
    ],
  },
  {
    id: "admBuzzer",
    group: "ADM controls",
    title: "Buzzer",
    method: "POST",
    endpoint: "/api/adm/buzzer",
    protected: true,
    risk: "hardware-write",
    focus: { area: "navigationLights" },
    description: "Sound the buzzer once or with a custom frequency and timing pattern.",
    defaultBody: {
      control: "buzzer",
      cmd: { status: 1, time: 1, mode: "standard", freq: 1500, timeOn: 80, timeOff: 120 },
    },
    controls: [
      {
        path: ["cmd", "status"],
        label: "Status",
        type: "select",
        options: [
          { value: 0, label: "Off" },
          { value: 1, label: "On" },
        ],
      },
      { path: ["cmd", "time"], label: "Times", type: "number", min: 0, max: 255 },
      {
        path: ["cmd", "mode"],
        label: "Mode",
        type: "select",
        options: [
          { value: "standard", label: "Standard" },
          { value: "custom", label: "Custom" },
        ],
      },
      { path: ["cmd", "freq"], label: "Frequency (Hz)", type: "number", min: 0, max: 65535 },
      { path: ["cmd", "timeOn"], label: "On time (ms)", type: "number", min: 0, max: 65535 },
      { path: ["cmd", "timeOff"], label: "Off time (ms)", type: "number", min: 0, max: 65535 },
    ],
  },
  {
    id: "admLock",
    group: "ADM controls",
    title: "Front door lock",
    method: "POST",
    endpoint: "/api/adm/lock",
    protected: true,
    risk: "hardware-motion",
    focus: { area: "pickupDoor", doorPath: null },
    description: "Open or close the front door lock for the requested duration.",
    defaultBody: { control: "lock", cmd: { status: 1, time: 15 } },
    controls: [
      {
        path: ["cmd", "status"],
        label: "Status",
        type: "select",
        options: [
          { value: 0, label: "Close" },
          { value: 1, label: "Open" },
        ],
      },
      { path: ["cmd", "time"], label: "Duration (s)", type: "number", min: 0, max: 255 },
    ],
  },
  {
    id: "sy600Lift",
    group: "SY600",
    title: "Lift target",
    method: "POST",
    endpoint: "/api/v1/sy600/c3/lift",
    protected: true,
    risk: "hardware-motion",
    focus: { area: "lift", targetPath: ["target"] },
    description: "Move/reset lift target. Common pickup targets are 85, 86, 87.",
    defaultBody: { target: 85 },
    controls: [
      {
        path: ["target"],
        label: "Target",
        type: "select",
        options: [
          { value: 0, label: "0 reset/reference" },
          { value: 1, label: "1 layer 1" },
          { value: 2, label: "2 layer 2" },
          { value: 3, label: "3 layer 3" },
          { value: 4, label: "4 layer 4" },
          { value: 5, label: "5 layer 5" },
          { value: 6, label: "6 layer 6" },
          { value: 7, label: "7 layer 7" },
          { value: 85, label: "85 pickup 1" },
          { value: 86, label: "86 pickup 2" },
          { value: 87, label: "87 pickup 3" },
        ],
      },
    ],
  },
  {
    id: "sy600MicroStep",
    group: "SY600",
    title: "Micro-step dispense",
    method: "POST",
    endpoint: "/api/v1/sy600/c4/micro-step",
    protected: true,
    risk: "hardware-motion",
    focus: {
      area: "slots",
      layerPath: ["layer"],
      channelStartPath: ["channelStart"],
      channelEndPath: ["channelEnd"],
      layerOffset: -1,
      channelOffset: 0,
    },
    description: "Run micro-step dispense across one layer/channel range.",
    defaultBody: { layer: 0, channelStart: 0, channelEnd: 0, repeat: 1 },
    controls: [
      { path: ["layer"], label: "Layer", type: "number", min: 0, max: 255 },
      { path: ["channelStart"], label: "Channel start", type: "number", min: 0, max: 255 },
      { path: ["channelEnd"], label: "Channel end", type: "number", min: 0, max: 255 },
      { path: ["repeat"], label: "Repeat", type: "number", min: 1, max: 100 },
    ],
  },
  {
    id: "sy600OutputDoor",
    group: "SY600",
    title: "Output door",
    method: "POST",
    endpoint: "/api/v1/sy600/c5/output-door",
    protected: true,
    risk: "hardware-motion",
    focus: { area: "outputDoor", doorPath: ["doorNo"] },
    description: "Open or close an output door.",
    defaultBody: { action: 1, doorNo: 1 },
    controls: [
      {
        path: ["action"],
        label: "Action",
        type: "select",
        options: [
          { value: 1, label: "Open" },
          { value: 0, label: "Close" },
        ],
      },
      { path: ["doorNo"], label: "Door", type: "number", min: 1, max: 255 },
    ],
  },
  {
    id: "sy600PickupDoor",
    group: "SY600",
    title: "Pickup door",
    method: "POST",
    endpoint: "/api/v1/sy600/c7/pickup-door",
    protected: true,
    risk: "hardware-motion",
    focus: { area: "pickupDoor", doorPath: ["doorNo"] },
    description: "Open or close a pickup door.",
    defaultBody: { action: 1, doorNo: 1 },
    controls: [
      {
        path: ["action"],
        label: "Action",
        type: "select",
        options: [
          { value: 1, label: "Open" },
          { value: 0, label: "Close" },
        ],
      },
      { path: ["doorNo"], label: "Door", type: "number", min: 1, max: 255 },
    ],
  },
  {
    id: "sy600Conveyor",
    group: "SY600",
    title: "Conveyor",
    method: "POST",
    endpoint: "/api/v1/sy600/c6/conveyor",
    protected: true,
    risk: "hardware-motion",
    focus: { area: "conveyor" },
    description: "Move conveyor forward or reverse for a bounded duration.",
    defaultBody: { direction: 0, seconds: 3 },
    controls: [
      {
        path: ["direction"],
        label: "Direction",
        type: "select",
        options: [
          { value: 0, label: "Forward" },
          { value: 1, label: "Reverse" },
        ],
      },
      { path: ["seconds"], label: "Seconds", type: "number", min: 0, max: 255 },
    ],
  },
  {
    id: "sy600ResetScan",
    group: "SY600",
    title: "Reset scan",
    method: "POST",
    endpoint: "/api/v1/sy600/24/reset-scan",
    protected: true,
    risk: "hardware-motion",
    focus: { area: "system" },
    description: "Reset door/lift flags and read machine structure.",
    defaultBody: { resetDoor: 1, resetLift: 1 },
    controls: [
      {
        path: ["resetDoor"],
        label: "Reset door",
        type: "select",
        options: [
          { value: 1, label: "Yes" },
          { value: 0, label: "No" },
        ],
      },
      {
        path: ["resetLift"],
        label: "Reset lift",
        type: "select",
        options: [
          { value: 1, label: "Yes" },
          { value: 0, label: "No" },
        ],
      },
    ],
  },
  {
    id: "sy600Infrared",
    group: "SY600 reads",
    title: "Infrared sensor",
    method: "POST",
    endpoint: "/api/v1/sy600/35/infrared",
    protected: true,
    risk: "read-via-serial",
    focus: { area: "sensors" },
    description: "Read one infrared/hall sensor class.",
    defaultBody: { sensorType: 0 },
    controls: [
      {
        path: ["sensorType"],
        label: "Sensor",
        type: "select",
        options: [
          { value: 0, label: "Drop" },
          { value: 1, label: "Platform 1" },
          { value: 2, label: "Anti-pinch 1" },
          { value: 4, label: "Platform 2" },
          { value: 5, label: "Anti-pinch 2" },
          { value: 6, label: "Platform 3" },
          { value: 7, label: "Anti-pinch 3" },
        ],
      },
    ],
  },
  {
    id: "sy600Microswitch",
    group: "SY600 reads",
    title: "Microswitch status",
    method: "GET",
    endpoint: "/api/v1/sy600/39/microswitch",
    protected: true,
    risk: "read-via-serial",
    focus: { area: "sensors" },
    description: "Read microswitch status bytes.",
    defaultBody: null,
    controls: [],
  },
  {
    id: "sy600Dispense",
    group: "SY600",
    title: "Channel dispense",
    method: "POST",
    endpoint: "/api/v1/sy600/28/dispense",
    protected: true,
    risk: "hardware-motion",
    focus: {
      area: "slots",
      channelStartPath: ["channelStart"],
      channelEndPath: ["channelEnd"],
    },
    description: "Dispense through SY600 channel range with 8-byte order id.",
    defaultBody: {
      layerAddressHex: "AABBCCDD",
      channelStart: 0,
      channelEnd: 0,
      orderIdHex: "0011223344556677",
    },
    controls: [
      { path: ["layerAddressHex"], label: "Layer address hex", type: "hex" },
      { path: ["channelStart"], label: "Channel start", type: "number", min: 0, max: 255 },
      { path: ["channelEnd"], label: "Channel end", type: "number", min: 0, max: 255 },
      { path: ["orderIdHex"], label: "Order id hex", type: "hex" },
    ],
  },
  {
    id: "sy600AckE0",
    group: "SY600 reads",
    title: "ACK E0",
    method: "POST",
    endpoint: "/api/v1/sy600/e0/ack",
    protected: true,
    risk: "read-via-serial",
    focus: { area: "system" },
    description: "Acknowledge active error report, optionally by address.",
    defaultBody: { addressHex: "AABBCCDD" },
    controls: [{ path: ["addressHex"], label: "Address hex", type: "hex" }],
  },
  {
    id: "cabinetLights",
    group: "Cabinet",
    title: "Cabinet lights",
    method: "POST",
    endpoint: "/api/v1/sy600/cabinet/lights",
    protected: true,
    risk: "hardware-write",
    focus: { area: "cabinetLights" },
    description: "Turn cabinet lights on or off (lamp 1 or 2).",
    defaultBody: { on: true, lamp: 1, addressHex: "00000000" },
    controls: [
      { path: ["on"], label: "Power", type: "boolean" },
      { path: ["lamp"], label: "Lamp", type: "number", min: 1, max: 2 },
      { path: ["addressHex"], label: "Address (Hex)", type: "text" },
    ],
  },
  {
    id: "cabinetStatus",
    group: "Cabinet",
    title: "Device status (0x44)",
    method: "POST",
    endpoint: "/api/v1/sy600/cabinet/status",
    protected: true,
    risk: "read-via-serial",
    focus: { area: "compressor" },
    description: "Query lights, glass heater, compressor cooling/heating, door, and defrost state.",
    defaultBody: { addressHex: "00000000" },
    controls: [
      { path: ["addressHex"], label: "Address (Hex)", type: "text" },
    ],
  },
  {
    id: "cabinetCompressor",
    group: "Cabinet",
    title: "Compressor",
    method: "POST",
    endpoint: "/api/v1/sy600/cabinet/compressor",
    protected: true,
    risk: "hardware-write",
    focus: { area: "compressor" },
    description: "Turn cabinet compressor on or off.",
    defaultBody: { on: true, addressHex: "00000000" },
    controls: [
      { path: ["on"], label: "Power", type: "boolean" },
      { path: ["addressHex"], label: "Address (Hex)", type: "text" },
    ],
  },
  {
    id: "cabinetCompressorTemperatureRead",
    group: "Cabinet",
    title: "Read compressor temperature",
    method: "POST",
    endpoint: "/api/v1/sy600/cabinet/compressor/temperature",
    protected: true,
    risk: "read-via-serial",
    focus: { area: "compressor" },
    description: "Read configured compressor temperature.",
    defaultBody: { read: true, addressHex: "00000000" },
    controls: [
      { path: ["addressHex"], label: "Address (Hex)", type: "text" },
    ],
  },
  {
    id: "cabinetCompressorTemperatureSet",
    group: "Cabinet",
    title: "Set compressor temperature",
    method: "POST",
    endpoint: "/api/v1/sy600/cabinet/compressor/temperature",
    protected: true,
    risk: "hardware-write",
    focus: { area: "compressor" },
    description: "Set compressor target temperature in Celsius.",
    defaultBody: { celsius: 8, addressHex: "00000000" },
    controls: [
      { path: ["celsius"], label: "Celsius", type: "number", min: 0, max: 255 },
      { path: ["addressHex"], label: "Address (Hex)", type: "text" },
    ],
  },
  {
    id: "drugDispenser",
    group: "Vending flow",
    title: "Drug dispenser API",
    method: "POST",
    endpoint: "/api/v1/vending/drugDispenser",
    protected: true,
    risk: "hardware-motion",
    focus: { area: "slots", doorPath: ["doorNo"] },
    description: "Run high-level dispenser order flow through existing vending service.",
    defaultBody: {
      prescription: "MANUAL-TEST-001",
      type: "manual-test",
      doorNo: 1,
      items: [
        {
          layer: 1,
          channelStart: 0,
          channelEnd: 0,
          qty: 1,
        },
      ],
    },
    controls: [
      { path: ["prescription"], label: "Prescription", type: "text" },
      { path: ["doorNo"], label: "Door", type: "number", min: 1, max: 255 },
    ],
  },
];

export const MANUAL_TEST_FLOWS = [
  {
    id: "preflight",
    title: "Preflight read-only",
    description: "Read HTTP health and queue state before hardware commands.",
    requiresExecuteConfirmation: false,
    steps: [
      { commandId: "health" },
      { commandId: "jobQueue" },
    ],
  },
  {
    id: "navigation-light-sweep",
    title: "Navigation light sweep",
    description: "Mark full LED range, then focus first, middle, and last ranges.",
    requiresExecuteConfirmation: true,
    steps: [
      { commandId: "health" },
      {
        commandId: "navigationLightsNoWait",
        body: { data: { act: "led", cmd: [1, 165, 0, 40, 180, 0] } },
      },
      {
        commandId: "navigationLightsNoWait",
        body: { data: { act: "led", cmd: [1, 12, 220, 120, 0, 1] } },
      },
      {
        commandId: "navigationLightsNoWait",
        body: { data: { act: "led", cmd: [76, 92, 220, 120, 0, 1] } },
      },
      {
        commandId: "navigationLightsNoWait",
        body: { data: { act: "led", cmd: [154, 165, 220, 120, 0, 1] } },
      },
      { commandId: "jobQueue" },
    ],
  },
  {
    id: "door-output-cycle",
    title: "Output door cycle",
    description: "Move lift to pickup 1, open output door 1, then close it.",
    requiresExecuteConfirmation: true,
    steps: [
      { commandId: "health" },
      { commandId: "sy600Lift", body: { target: 85 } },
      { commandId: "sy600OutputDoor", body: { action: 1, doorNo: 1 } },
      { commandId: "sy600OutputDoor", body: { action: 0, doorNo: 1 } },
      { commandId: "jobQueue" },
    ],
  },
  {
    id: "sensor-read",
    title: "Sensor read pass",
    description: "Read microswitch and drop infrared status through SY600.",
    requiresExecuteConfirmation: true,
    steps: [
      { commandId: "health" },
      { commandId: "sy600Microswitch" },
      { commandId: "sy600Infrared", body: { sensorType: 0 } },
      { commandId: "jobQueue" },
    ],
  },
];

export function getManualTestCatalog() {
  return {
    commands: MANUAL_TEST_COMMANDS,
    flows: MANUAL_TEST_FLOWS,
  };
}
